import argparse
import json
import os
import sys
from pathlib import Path

try:
    import requests
except ImportError as exc:
    raise ImportError("Please install requests: pip install requests") from exc


def load_cache(path: Path) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def call_deepseek_summary(concatenated: str) -> str:
    api_key = os.getenv("DEEPSEEK_API_KEY")
    if not api_key:
        return "DeepSeek summary failed: DEEPSEEK_API_KEY not set."

    url = "https://api.deepseek.com/chat/completions"
    prompt = (
        "请根据以下章节总结内容，生成一份不超过500字的整体总结，用中文撰写，请保持流畅和连贯性：\n\n"
        f"{concatenated}"
    )
    payload = {
        "model": "deepseek-chat",
        "messages": [{"role": "user", "content": prompt}],
    }
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }

    try:
        response = requests.post(url, headers=headers, json=payload, timeout=60)
        response.raise_for_status()
        body = response.json()
        return body["choices"][0]["message"]["content"]
    except Exception as exc:
        return f"DeepSeek summary failed: {exc}"


def format_answers(answers: dict) -> str:
    lines = []
    for key in sorted(answers, key=lambda k: int(k)):
        entry = answers[key]
        title = entry.get("title") or f"Section {int(key) + 1}"
        href = entry.get("href", "Unknown source")
        answer = entry.get("answer", "").strip()
        lines.append(f"### {title}")
        lines.append(f"- Source: {href}")
        lines.append(answer)
        lines.append("")
    return "\n".join(lines).strip()


def format_qa_logs(qa_logs: dict) -> str:
    sections = []
    for chapter_key in sorted(qa_logs, key=lambda k: int(k)):
        entries = qa_logs.get(chapter_key) or []
        for entry in entries:
            title = entry.get("chapter_title", f"Section {int(chapter_key) + 1}")
            question = entry.get("question", "")
            answer = entry.get("answer", "")
            asked_at = entry.get("asked_at", "unknown")
            answered_at = entry.get("answered_at", "unknown")
            sections.append(f"### Q&A for {title}")
            sections.append(f"**Q:** {question}  ")
            sections.append(f"**A:** {answer}  ")
            sections.append(f"- asked_at: {asked_at}  ")
            sections.append(f"- answered_at: {answered_at}")
            sections.append("---")
    return "\n".join(sections).strip()


def build_markdown(book_id: str, summary: str, answers_md: str, qa_md: str) -> str:
    return "\n".join(
        [
            f"# {book_id}_reading_note",
            "## by epub_AI_reader",
            "",
            "## Recap (generated by DeepSeek)",
            summary,
            "",
            "## Chapter Summaries",
            answers_md,
            "",
            "## QA Log",
            qa_md,
        ]
    )


def main():
    parser = argparse.ArgumentParser(description="Export default AI cache to a Markdown note.")
    parser.add_argument(
        "--cache",
        default="llibrary/data/Antifragile_date/default_ai_cache.json",
        help="Path to default_ai_cache.json (defaults to library/data/Antifragile_date/default_ai_cache.json).",
    )
    args = parser.parse_args()

    cache_path = Path(args.cache)
    if not cache_path.exists():
        print(f"Cache file not found: {cache_path}", file=sys.stderr)
        sys.exit(1)

    cache = load_cache(cache_path)
    book_id = cache.get("book_id") or cache_path.stem
    answers = cache.get("answers", {})
    qa_logs = cache.get("qa_logs", {})

    concatenated = "\n\n".join(
        entry.get("answer", "").strip() for key, entry in sorted(
            answers.items(), key=lambda pair: int(pair[0])
        ) if entry.get("answer")
    )

    if not concatenated:
        summary = "DeepSeek summary failed: no answers available."
    else:
        summary = call_deepseek_summary(concatenated)

    answers_md = format_answers(answers)
    qa_md = format_qa_logs(qa_logs)
    markdown = build_markdown(book_id, summary, answers_md, qa_md)
    output_path = Path(f"notes/{book_id}_reading_note.md")

    output_path.write_text(markdown, encoding="utf-8")
    print(f"Written note to {output_path}")


if __name__ == "__main__":
    main()
